#include "AtlasTileEditor.h"

Zint stashed_bigsquare,stashed_grid22,stashed_grid44,stashed_grid88,stashed_grid1616,stashed_gridAtlas,stashed_grid_square64,stashed_grid_square64b,stashed_grid_square64c,stashed_grid_square64d;