#define AGK_KEY_BACK			0x08
#define AGK_KEY_TAB				0x09
#define AGK_KEY_ENTER			0x0D
#define AGK_KEY_SHIFT			0x10
#define AGK_KEY_CONTROL			0x11
#define AGK_KEY_ALT				0x12
#define AGK_KEY_ESCAPE			0x1B
#define AGK_KEY_SPACE			0x20
#define AGK_KEY_PAGEUP			0x21
#define AGK_KEY_PAGEDOWN		0x22
#define AGK_KEY_END				0x23
#define AGK_KEY_HOME			0x24
#define AGK_KEY_LEFT			0x25
#define AGK_KEY_UP				0x26
#define AGK_KEY_RIGHT			0x27
#define AGK_KEY_DOWN			0x28
#define AGK_KEY_INSERT			0x2D
#define AGK_KEY_DELETE			0x2E

#define AGK_KEY_0				0x30
#define AGK_KEY_1				0x31
#define AGK_KEY_2				0x32
#define AGK_KEY_3				0x33
#define AGK_KEY_4				0x34
#define AGK_KEY_5				0x35
#define AGK_KEY_6				0x36
#define AGK_KEY_7				0x37
#define AGK_KEY_8				0x38
#define AGK_KEY_9				0x39

#define AGK_KEY_A				0x41
#define AGK_KEY_B				0x42
#define AGK_KEY_C				0x43
#define AGK_KEY_D				0x44
#define AGK_KEY_E				0x45
#define AGK_KEY_F				0x46
#define AGK_KEY_G				0x47
#define AGK_KEY_H				0x48
#define AGK_KEY_I				0x49
#define AGK_KEY_J				0x4A
#define AGK_KEY_K				0x4B
#define AGK_KEY_L				0x4C
#define AGK_KEY_M				0x4D
#define AGK_KEY_N				0x4E
#define AGK_KEY_O				0x4F
#define AGK_KEY_P				0x50
#define AGK_KEY_Q				0x51
#define AGK_KEY_R				0x52
#define AGK_KEY_S				0x53
#define AGK_KEY_T				0x54
#define AGK_KEY_U				0x55
#define AGK_KEY_V				0x56
#define AGK_KEY_W				0x57
#define AGK_KEY_X				0x58
#define AGK_KEY_Y				0x59
#define AGK_KEY_Z				0x5A

#define AGK_KEY_F1				0x70
#define AGK_KEY_F2				0x71
#define AGK_KEY_F3				0x72
#define AGK_KEY_F4				0x73
#define AGK_KEY_F5				0x74
#define AGK_KEY_F6				0x75
#define AGK_KEY_F7				0x76
#define AGK_KEY_F8				0x77

// 3D constants
#define AGK_DEPTH_NEVER 0
#define AGK_DEPTH_LESS 1
#define AGK_DEPTH_EQUAL 2
#define AGK_DEPTH_LEQUAL 3
#define AGK_DEPTH_GREATER 4
#define AGK_DEPTH_NOTEQUAL 5
#define AGK_DEPTH_GEQUAL 6
#define AGK_DEPTH_ALWAYS 7

#define AGK_BLEND_ZERO 0
#define AGK_BLEND_ONE 1
#define AGK_BLEND_SRC_ALPHA 2
#define AGK_BLEND_ONE_MINUS_SRC_ALPHA 3
#define AGK_BLEND_DST_ALPHA 4
#define AGK_BLEND_ONE_MINUS_DST_ALPHA 5
#define AGK_BLEND_SRC_COLOR 6
#define AGK_BLEND_ONE_MINUS_SRC_COLOR 7
#define AGK_BLEND_DST_COLOR 8
#define AGK_BLEND_ONE_MINUS_DST_COLOR 9
#define AGK_BLEND_ALPHA_SATURATE 10