
// -*- C++ -*-
// $Id: Version.h 84362 2009-02-09 18:01:40Z mesnier_p $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.

#define ACE_MAJOR_VERSION 5
#define ACE_MINOR_VERSION 6
#define ACE_BETA_VERSION 8
#define ACE_VERSION "5.6.8"
